FROM python:3.8-slim AS test-image
EXPOSE 8080
RUN mkdir app
WORKDIR /app
COPY . .
RUN pip install --user -r requirements_test.txt
RUN python -m pytest

FROM python:3.7-slim AS build-image
COPY --from=test-image /app /app
WORKDIR /app
RUN pip install --user -r requirements.txt
ENTRYPOINT ["python"]
CMD ["app.py"]